---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool:fedora
    ports:
    - containerPort: 80
      protocol: TCP 
    envFrom:
      - secretRef:
          name: secret-vault
  restartPolicy: Never
