# node.name: "elasticsearch-hot"
# cluster.name: ${CLUSTER_NAME}
# network.host: 0.0.0.0
# cluster.initial_master_nodes: "elasticsearch-hot,elasticsearch-warm"
# discovery.seed_hosts: "elasticsearch-warm"
# bootstrap.memory_lock: true
# xpack.security.enabled: true
# xpack.license.self_generated.type: ${LICENSE}