all:
  hosts:
    kubemaster:
      ansible_host: 192.168.121.30
      ip: 192.168.121.30
      access_ip: 192.168.121.30
      ansible_user: vagrant
    kubenode1:
      ansible_host: 192.168.121.123
      ip: 192.168.121.123
      access_ip: 192.168.121.123
      ansible_user: vagrant
    kubenode2:
      ansible_host: 192.168.121.2
      ip: 192.168.121.2
      access_ip: 192.168.121.2
      ansible_user: vagrant
  children:
    kube_control_plane:
      hosts:
        kubemaster:
    kube_node:
      hosts:
        kubenode1:
        kubenode2:
    etcd:
      hosts:
        kubemaster:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
