# server.name: "kibana"
# server.host: 0.0.0.0
# server.publicBaseUrl: "http://localhost:5601"
# elasticsearch.hosts: [ "http://elasticsearch-hot:9200" ]
# monitoring.ui.container.elasticsearch.enabled: true
# #elasticsearch.ssl.verificationMode: "none"