---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool:latest
    ports:
    - containerPort: 22
      protocol: TCP
    env:
    - name: TEST_ENV
      valueFrom: 
        secretKeyRef:
            name: secret-env
            key: TEST_ENV
            optional: false       
    volumeMounts:
      - name: test-vol
        mountPath: "/opt/secret"
        readOnly: true
  volumes:
  - name: test-vol
    secret:
      secretName: secret-prod
      optional: false