{
 "title": "monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "LA1m",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LA5m",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LA15m",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "100 * (1- avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FreeMem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes / on(instance) node_memory_MemTotal_bytes ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FreeSpaseDisc",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": " 100 - (irate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[5m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}