---
all:
  hosts:
    sonar-01:
      ansible_host: 192.168.121.87
    nexus-01:
      ansible_host: 192.168.121.165
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant