---
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: "http://elasticsearch-hot:9200"
xpack.monitoring.enabled: false
# # xpack.monitoring.elasticsearch.username: "logstash_internal"
# # xpack.monitoring.elasticsearch.password: ${LOGSTASH_INTERNAL_PASSWORD}" 